# Generated by Django 4.1.3 on 2022-12-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
